name: button
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  video_player: ^2.8.2
  webview_flutter: ^3.0.0 
  audioplayers: ^5.2.1
  vibration: ^1.7.3
  
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - sounds/
    - vedios/
 